Start working on trendings environments
avorty/spito-gui pull request #14
Opened 2024-01-25 08:40 UTC by maxidragon

2024-01-25 12:25 UTC, Majkipl27 requested changes

2024-01-25 12:25 UTC, Majkipl27 commented on src/renderer/src/Layout/Header.tsx
Please remove also the navlink in the responsive view.

2024-01-26 08:23 UTC, maxidragon commented on src/renderer/src/Pages/Profile/Components/Environment.tsx
> +                    title="Edit ruleset"
```suggestion
                    title="Edit environment"
```

2024-01-26 08:23 UTC, maxidragon commented on src/renderer/src/Pages/Profile/Components/Environment.tsx
> +                    title="Delete ruleset"
```suggestion
                    title="Delete environment"
```

2024-01-26 10:04 UTC, maxidragon commented on src/renderer/src/Pages/SavedEnvironments/SavedEnvironments.tsx
> +export default function SavedEnvieonments(): JSX.Element {
```suggestion
export default function SavedEnvironments(): JSX.Element {
```

Remember to change all references too

2024-01-26 10:04 UTC, maxidragon commented on src/renderer/src/Pages/Profile/Components/Environment.tsx
> +              className={`${
Please use `twMerge` function

2024-01-26 10:04 UTC, maxidragon commented on src/renderer/src/Pages/Profile/Components/Environment.tsx
> +            className={`${
See above

2024-01-26 10:10 UTC, maxidragon commented
LGTM

2024-01-26 10:11 UTC, merged