Create more functions to communicate with cli
avorty/spito-gui pull request #20
Opened 2024-02-23 11:14 UTC by cooligus

2024-02-24 22:48 UTC, BaderBC requested changes

2024-02-24 22:48 UTC, BaderBC commented on src-tauri/src/spito_helper.rs
> +    revert_number: i32,
```suggestion
    revert_number: u32,
```

2024-02-26 15:00 UTC, maxidragon approved these changes

2024-02-26 15:10 UTC, BaderBC approved these changes

2024-02-26 15:22 UTC, merged